---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: "fluentd"
    static_configs:
      - targets: ["fluentd:24231"]
  - job_name: "fluent-bit-prom"
    static_configs:
      - targets: ["fluent-bit:2021"]
  - job_name: "fluent-bit-builtin"
    static_configs:
      - targets: ["fluent-bit:2020"]
    metrics_path: "/api/v1/metrics/prometheus"
